# Defines the shared ordered feature schema used by model seeding and inference.

DEFAULT_FEATURE_ORDER = (
    "Flesch Reading Ease",
    "Dale-Chall Readability Score",
    "SMOG Index",
    "Automated Readability Index",
    "Sentiment (mean)",
    "Sentiment (10th)",
    "Sentiment (50th)",
    "Sentiment (75th)",
    "Sentiment (90th)",
    "Number of organizations mentioned",
    "Number of named individuals",
    "Number of countries or regions mentioned",
    "Word count",
    "Paragraph count",
    "PERSON",
    "NORP",
    "FAC",
    "ORG",
    "GPE",
    "LOC",
    "PRODUCT",
    "EVENT",
    "WORK_OF_ART",
    "LAW",
    "LANGUAGE",
    "DATE",
    "TIME",
    "PERCENT",
    "MONEY",
    "QUANTITY",
    "ORDINAL",
    "CARDINAL",
)
